name: stars_wars_info
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dio: ^5.1.2
  json_annotation: ^4.8.1
  flex_color_scheme: ^7.0.5
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  fpdart: ^0.6.0
  go_router: ^7.0.0
  google_fonts: ^4.0.4
  pretty_dio_logger: ^1.3.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  flutter_gen: ^5.3.1
  flutter_lints: ^2.0.1
  freezed: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
